### ISSUE TITLE
Scanning a string with comma separated numbers lists :error instead of the comma character

### ISSUE THREAD

**Issue by DaTrader** [elixir-cldr/cldr_numbers#19]
ex:
```
iex(21)> Cldr.Number.Parser.scan( "Here's my number list: 1, 2, 3, 4, 5", number: :decimal)
["Here's my number list: ", #Decimal<1>, :error, #Decimal<2>, :error,
 #Decimal<3>, :error, #Decimal<4>, :error, #Decimal<5>]

```
The (only) locale used is "en" as per the following Cldr config:
```
defmodule MyApp.Cldr do
  use Cldr,
      default_locale: "en",
      locales: [ "en"],
      add_fallback_locales: false,
      gettext: MyApp.Gettext,
      data_dir: "./priv/cldr",
      otp_app: :engage,
      precompile_number_formats: [ "¤#,##0.##"],
      precompile_transliterations: [],
      providers: [ Cldr.Number, Cldr.Territory],
      generate_docs: true,
      force_locale_download: false
end
```

PS. Unrelated, but is it ok that :CAD formatting is CA$ instead of C$, for :AUD gets correctly formatted to A$? Also, there are formatting examples in the docs that format to C$ not CA$.

**Comment by kipcole9** [comment]
Thanks for the report, I'll dig into the parsing code for the example you gave.

On the "unrelated" note, both the "en" and "en-001" locales both can `CA$` as the symbol for Canadian dollar (and  `$` for the narrow symbol).  They both also have `A$` for Australian dollar as you noted.  These are data that come from CLDR so not something I can change.   If its for financial tables than you can use the `currency_format: :iso` that will use `CAD` and `AUD` instead of symbols. But thats not a great user experience for a consumer-facing application.

**Comment by kipcole9** [comment]
The doctests all pass so when you say some examples in the docs are incorrect do you mean the readme.md file? I will check those by hand if thats where you see some possible errors.

**Comment by DaTrader** [comment]
Yes, in the notes: https://hexdocs.pm/ex_cldr_numbers/readme.html#notes

Is it anyhow possible for the user to configure currency formatting for CAD into C$ instead of CA$ i.e. to override the CLDR data?

**Comment by DaTrader** [comment]
Btw, the (misfortunate) French single white space character for the thousands separator is not recognized when parsing with the French locale, i.e. the parser scans as if 12 345 are two numbers instead of one. I can imagine why this may be a problem to implement but just saying, in case it was supposed to work.

**Comment by DaTrader** [comment]
And btw, I am amazed by your effort invested into the library. Regardless of the minor bugs, it's simply fantastic. Saves tons of time. Thanks for that!

**Comment by kipcole9** [comment]
Actually, it's supposed to work.  Curious, my simple round-trip appears to work (there is a non-breaking space in there, trust me!):
```elixir
iex> Cldr.Number.to_string 12345, locale: "fr"      
{:ok, "12 345"}
iex> Cldr.Number.Parser.parse "12 345", locale: "fr"
{:ok, 12345}
```

**Comment by DaTrader** [comment]
Re: French parsing:
```
iex(3)> Cldr.Number.Parser.scan( "This is one number 12 345", locale: "fr")
["This is one number ", 12, " ", 345]

```
(I did compile with the "fr" locale added before trying the aboe)

**Comment by kipcole9** [comment]
Ahhhh, `Cldr.Number.Parser.scan/2` -> I hate this code because it uses a regex not a formal parser. I'll see what I can do.

**Comment by kipcole9** [comment]
As of commit [5a1e9ac](https://github.com/elixir-cldr/cldr_numbers/commit/5a1e9acbf2bf31511c1c4670b6b14eba26b07bba) I believe that both issues are resolved. 

#### Parsing a list of numbers separated by commas
```elixir
# Note that is correctly parses a number list when the "," is not followed by
# a digit. It also correctly parses numbers that have a ",".
iex> Cldr.Number.Parser.scan( "Here's my number list: 1111, 2222, 3333, 4444, 55,55", number: :decimal)
["Here's my number list: ", #Decimal<1111>, ", ", #Decimal<2222>, ", ",
 #Decimal<3333>, ", ", #Decimal<4444>, ", ", #Decimal<5555>]

#### Parsing in locales that have a non-breaking space as a separator
I believe the existing code is working correctly. The key is that the grouping separator in the "fr" locale (also the "de" locale and others is a [non-breaking-space](https://en.wikipedia.org/wiki/Non-breaking_space) which is code point `U+00A0`. A "normal" space is code point `U+0020`.
```elixir
iex>  Cldr.Number.Parser.scan( "This is one number 12 345", locale: "fr")
["This is one number ", 12345]
```
There isn't really a way to parse a string for numbers that use `U+0020` as a grouping separator, its too ambiguous.

I will work on the "custom currency symbol" now in another commit.  Feel free to try out the code from the master branch. I expect to push a new release within 24 hours when I get this next commit done.

**Comment by kipcole9** [comment]
I don't think CLDR is at fault here. A non-breaking space is exactly what you want when you're formatting numbers in a locale that uses a space as a grouping character. It would be horrible to have word-wrap in a sentence containing numbers occurring in the middle of a number!

For the purposes of scanning a string for numbers, the key objective is to split the string at what look to be number boundaries. And to do so in a localised manner. In case someone else treads this path in the future, here is what happens:

#### Localised scanning of string for numbers

1. Start with a template regex that tries to recognise number boundaries leniently. As of this date, the regex looks like `"[-+]?[0-9]([0-9_]|[,](?=[0-9]))*(\\.?[0-9_]+([eE][-+]?[0-9]+)?)?"` which roughly says "might start with a + or -, then a bunch of digits or underscore or comma, as long as the comma is followed by a digit. Then potentially a fraction and an exponent.
2. Localise the regex.  In order to reflect the expectations of a given locale, the group symbol and the decimal separator have to be replaced with the locale equivalents.
3. Add lenient parse alternatives for grouping, +/- and decimal separator. To reflect that Unicode has multiple ways of expressing these symbols with different code points that are in use in different locales, CLDR captures as best it can the symbols that might be found.  For example in the locale "fr" we can see:
```elixir
iex> MyApp.Cldr.lenient_parse_map :number, "fr"                         
%{
  "+" => ~r/[+⁺₊➕﬩﹢＋]/u,
  "," => ~r/[,،٫、︐︑﹐﹑，､]/u,
  "_" => ~r/[\-‒⁻₋−➖﹣－]/u
}
```
4. Replace the localised number system with latin digits. Different locales use different number systems. At current count there are 85 number systems in use in CLDR.
```elixir
iex> Cldr.Number.System.known_number_systems
[:adlm, :ahom, :arab, :arabext, :armn, :armnlow, :bali, :beng, :bhks, :brah,
 :cakm, :cham, :cyrl, :deva, :diak, :ethi, :fullwide, :geor, :gong, :gonm,
 :grek, :greklow, :gujr, :guru, :hanidays, :hanidec, :hans, :hansfin, :hant,
 :hantfin, :hebr, :hmng, :hmnp, :java, :jpan, :jpanfin, :jpanyear, :kali, :khmr,
 :knda, :lana, :lanatham, :laoo, :latn, :lepc, :limb, :mathbold, :mathdbl,
 :mathmono, :mathsanb, ...]
```

As a result, in the French locale our basic regex goes from:
```elixir
"[-+]?[0-9]([0-9_]|[,](?=[0-9]))*(\\.?[0-9_]+([eE][-+]?[0-9]+)?)?"
```
to a fully localised, lenient parse version that is actually used (but is quite incomprehensible!):
```elixir
"[+⁺₊➕﬩﹢＋\\-‒⁻₋−➖﹣－]?[0-9]([0-9_]|[,،٫、︐︑﹐﹑，､ ](?=[0-9]))*(\\,?[0-9_]+([eE][+⁺₊➕﬩﹢＋\\-‒⁻₋−➖﹣－]?[0-9]+)?)?"
```

#### Where to from here?

The question you are asking is "can we also use a U+0020 normal space as a grouping separator and therefore recognise that in a string "10 20" should be interpreted as "1020".  I think the answer to that might be "probably" - as long as there are no locales that us U+0020 as a list separator (in the way we use "," as a list separator in English).

I'll run some code over the CLDR repository and see what list separators are defined in all ~500 locales and come back to this.

**Comment by kipcole9** [comment]
Turns out many locales use U+0020 as a list separator. Typically for the list type of "unit_narrow". Which makes me concerned that allowing a U+0020 as a grouping separator when scanning a string for numbers would introduce more issues than it solves.

Thoughts?

**Comment by kipcole9** [comment]
As of commit [6b3cd02](https://github.com/elixir-cldr/cldr_numbers/commit/6b3cd025a940aea77b866df37e2e2d1cde3b0f16) there are now additional value `:currency_symbol` options to `Cldr.Number.to_string/3`. From the revised documentation:

### Currency symbol option

* `currency_symbol`: Allows overriding a currency symbol. The alternatives
          are:
  * `:iso` the ISO currency code will be used instead of the default currency symbol.
  * `:narrow` uses the narrow symbol defined for the locale. The same narrow symbol can be defined for more than one currency and therefore this should be used with care. If no narrow symbol is defined, the standard symbol is used.
  * `:symbol` uses the standard symbol defined in CLDR. A symbol is unique for each currency and can be safely used.
  * "string" uses `string` as the currency symbol
  * `:standard` (the default and recommended) uses the CLDR-defined symbol based upon the currency format for the locale.

### Examples

```elixir
iex> Cldr.Number.to_string 1234, currency: :AUD, currency_symbol: :narrow  
{:ok, "$1,234.00"}

iex> Cldr.Number.to_string 1234, currency: :AUD, currency_symbol: :standard
{:ok, "A$1,234.00"}

iex> Cldr.Number.to_string 1234, currency: :AUD, currency_symbol: :symbol  
{:ok, "A$1,234.00"}

iex> Cldr.Number.to_string 1234, currency: :AUD, currency_symbol: :iso     
{:ok, "AUD 1,234.00"}

iex> Cldr.Number.to_string 1234, currency: :AUD, currency_symbol: "CUSTOM" 
{:ok, "CUSTOM 1,234.00"}
```

I'll leave this issue open for a few hours in case you have any comments or suggestions. Otherwise I will close this issue and publish a new release.

**Comment by DaTrader** [comment]
The suggested solution for custom currency symbols is just fine. As for the non-breaking space issue, maybe reconsider it in another release. My logic here is that it should never be the case (and there probably isn't one) of a locale with a non-breaking space used as both the group and list separator.

**Comment by kipcole9** [comment]
Thanks for the feedback.  

I have been reflecting on this too and am experimenting with the idea that if the grouping symbol for the locale is a non-breaking-space, also allow 0x20 as a grouping indicator when parsing.  I will finish up that experiment this evening my time. I think that will work acceptably and if so I'll push that out the door in the next few hours.

**Comment by kipcole9** [comment]
OK, experiment complete and [ex_cldr_numbers version 2.20.0](https://hex.pm/packages/ex_cldr_numbers/2.20.0) has been published. Thanks for the collaboration and support of the project.

### Bug Fixes

* Improve number parsing with `Cldr.Number.Parser.scan/2` when the string has lists of numbers separated by commas.  Thanks to @DaTrader for the report. Closes #19.

### Enhancements

* Add support for custom currency symbols. This extends the use of the `:currency_symbol` option. In previousl releases this option was required to be `:standard` or `:iso`. Now the value can also be `:narrow`, `:symbol` or a string which will be used as the currency symbol.  From the documentation for `Cldr.Number.to_string/3`:

  * `currency_symbol`: Allows overriding a currency symbol. The alternatives
    are:
    * `:iso` the ISO currency code will be used instead of the default
      currency symbol.
    * `:narrow` uses the narrow symbol defined for the locale. The same
      narrow symbol can be defined for more than one currency and therefore this
      should be used with care. If no narrow symbol is defined, the standard
      symbol is used.
    * `:symbol` uses the standard symbol defined in CLDR. A symbol is unique
      for each currency and can be safely used.
    * "string" uses `string` as the currency symbol
    * `:standard` (the default and recommended) uses the CLDR-defined symbol
      based upon the currency format for the locale.

**Comment by kipcole9** [comment]
Turns out the "fr" locale actually uses something called a [pop space](https://codepoints.net/U+202C?lang=en), not [non-breaking space](https://codepoints.net/U+00A0?lang=en).  Parsing in locales where the grouping character is a `pop space` will now also support an `ascii space (0x20)` as well.  Test cases were added.

**Comment by DaTrader** [comment]
Yes, both features work properly now. Will continue testing the library for my UC.

Btw, not sure if this is the expected behavior with resolve_currencies/2 (shouldn't the US dollars be recognized as well?):

```
iex(7)> Cldr.Number.Parser.scan( "Lets try this 123 US dollars and this 345 euros") |> Cldr.Number.Parser.resolve_currencies()
["Lets try this ", 123, " US dollars and this ", 345, :EUR]
```

Also, have you considered supporting percentages as decimals/floats with a function like resolve_percentages/2 after the initial scan? Also, in my app, I ("manually") provide support for parsing and formatting percentages and multiples, and also take bps in addition to of the ‰ character as it is easier and more common for the users to use bps.

Not my intention to use this github issue as a thread, but while at it, I also took a look at your other libraries, namely Date/Time and Territories. I saw the support for quarters in Date/Time as in 2Q. But does the date/time formatting also support formatting like 2Q21 21Q2 Y1Q2 1Q2Y? I have all these implemented in a proprietary manner at the app level (not as a library) but I believe they would be very useful in financial reporting for other users as well so I figured you may consider adding them in a future release as, unlike mine, your approach to the subject is standard based, and I for first would be more than happy to switch over to your other libraries.

**Comment by kipcole9** [comment]
Yes, "US dollars" should be recognised.  The string match is currently done by default on a string equality test on each element of the scanned result. So " US dollars and this " doesn't equal any currency string.  You can `Cldr.Number.Parser.resolve_currencies(fuzzy: 0.8)` and it will match with `US dollars` but you would then lose the test " and this " which I assume is undesirable.

```elixir
iex> Cldr.Number.Parser.scan( "Lets try this 123 US dollars and this 345 euros") 
...|> Cldr.Number.Parser.resolve_currencies(fuzzy: 0.8)
["Lets try this ", 123, :USD, 345, :EUR]
```

I will take this as an improvement request and have started some work to identify currency strings at the start of end of a longer string.

> Also, have you considered supporting percentages as decimals/floats with a function like resolve_percentages/2 after the initial scan?

Yes, but its not high on my priority list. If thats the last open item I'll give it some thought and see what I can do over the weekend.

I have moved the dates/times question to its [own issue](https://github.com/elixir-cldr/cldr_dates_times/issues/24) and answered you there.

**Comment by kipcole9** [comment]
As of commit [6a8f8a0](https://github.com/elixir-cldr/cldr_numbers/commit/6a8f8a0250a9ebe226d1898b34ef0ca7d65fa299), currency names at either the beginning and/or end of a string are extracted.
```elixir
iex> scanned = Cldr.Number.Parser.scan( "Lets try this 123 US dollars, a bunch of swiss francs 23 and 345 euros")
iex> Cldr.Number.Parser.resolve_currencies(scanned)
["Lets try this ", 123, :USD, ", a bunch of ", :CHF, 23, " and ", 345, :EUR]
```

**Comment by kipcole9** [comment]
I will take a look at `%` and `‰` scanning now too.  I am not very comfortable with using abbreviations because unless they are supported in CLDR, there is no localised way to scan for abbreviations.

My thinking is to scan the strings and extract them as `:percent` and `:permille` in the same way as a currency is encoded as `:USD`.  How the symbols are interpreted downstream is then up to the developer. I don't automatically create `Money` structs from a currency and an amount and I don't think I should be automatically calculating percentages and permilles either.

Thoughts?

**Comment by DaTrader** [comment]
Even better! No need to turn them into actual characters, just to extract them as such.

**Comment by kipcole9** [comment]
I have published [ex_cldr_number version 2.21.0](https://github.com/elixir-cldr/cldr_numbers/releases/tag/v2.21.0) with the following changelog entry:

### Enhancements

* Add `Cldr.Number.Parser.resolve_pers/2` which will tokenize percent and permille symbols into `:percent` and `:permille`. This is similar to the `Cldr.Number.Parser.resolve_currencies/2` function but for percent and permille symbols. An example is:

```elixir
iex> Cldr.Number.Parser.scan("100%")
...> |> Cldr.Number.Parser.resolve_pers()
[100, :percent]
```
The implementation uses the [CLDR lenient parse data](http://cldr.unicode.org/translation/-core-data/characters) which means it can be passed the various different codepoints for percent and permille.

**Comment by DaTrader** [comment]
I think there's a bug with scanning currency names as I believe the following not be the case:
```
iex(51)> Cldr.Number.Parser.scan( "asdUS dollars")
["asdUS dollars"]
```
It's ok when it does so when next to punctuation characters, but not when effectively a part of another word.

**Comment by kipcole9** [comment]
Ah, took me a while (been working on math for calculating lunar astronomy and my head hurts) but I see what you mean.

I need to think on how best to do this.  I have the Unicode break algorithm implemented (in [unicode_string](https://github.com/elixir-unicode/unicode_string) which can detect if there is a word break before the currency code. But thats not a small package so I'm reluctant to add it here.

To do what you suggest, its important to detect what a word break is. Whitespace, punctuation, symbols and so on. And not just limited to ASCII, or Latin-1; it needs to be fit for purpose for all locales and all scripts. `unicode_string` does that, but .... too much to be a required dependency I believe.

One approach is to have the developer break the strings into words before resolving currencies. That makes including `unicode_string` optional for when its required.

Another is to make `unicode_string` an optional dependency. If its configured, then implement word breaks before looking up currencies. If not, then don't. Also not optimal.

Thoughts?

**Comment by kipcole9** [comment]
The scope of the `Cldr.Number.Parser.scan/2` function is to scan text for numbers and money amounts. While I have had no issue expanding the scope to be more friendly to free text parsing, I also want to keep the right focus too.

I'm thinking actually that if you're working with arbitrary text and you're tokenising it, then starting with [Unicode.String.split/2](https://hexdocs.pm/unicode_string/Unicode.String.html#split/2) is probably better. After breaking up the text you could then enumerate it parsing numbers and looking up currency codes with much less ambiguity.

**Comment by DaTrader** [comment]
Actually, at first I found your library much more convenient for this task as I myself needed to write less app-specific code while depending on a reliable library (yours). However, I am naturally open to new suggestions. But even in that case, I still don't see how to deal with this particular problem given the current behavior, i.e. even I did split the text prior to scanning it for numbers, the problem would still persist.

Your suggestion of an optional dependency on Unicode.String sounds reasonable. Better yet, it would promote good practice.

**Comment by DaTrader** [comment]
Please keep in mind that thanks to your library I so far only need do the following:
1. Extract quoted text first (as it should be treated as literals)
2. Parse numbers (with resolving currencies and percentages/permilles)
3. Only now split all the untokenized text
4. Resolve/tokenize territories and my reserved terms

And that's really a beaut thanks to your libraries.

**Comment by DaTrader** [comment]
PS. Thanks to your library I can separate remaining literals into words and punctuation in a blanket fashion in phase 4) as by then all the currencies, numbers, money, my logical and comparison operators will have been tokenized already.

**Comment by kipcole9** [comment]
Sleep helped. Its not so complicated. All that was required was to check if the remaining string (after matching) started or ended with `[:alpha:]` which, in unicode mode, matches all scripts. Tests added and new version [ex_cldr_numbers v2.22.0](https://hex.pm/packages/ex_cldr_numbers/2.22.0) published.

Thanks for the comments above, it definitely helps motivation - this family of libraries has grown well beyond my original expectations of a weekend project :-) 

Note that you might find Cldr.Number.Parser.resolve/2` and `Cldr.Number.Parser.find_and_replace/2` useful for other parts of your work. I've made them public functions now and documented their use.  

Last thing, there is a package [ex_cldr_territories](https://hex.pm/packages/ex_cldr_territories) which hold localised territory (and subterritory) localise names. It might help you as well given you seem to be tokenising territory names. Let me know if you need some help navigating that.

### Enhancements

* `Cldr.Number.Parser.resolve_currencies/2` and `Cldr.Number.Parser.resolve_per/2` only perform replacements if the the found string is not adjacent to an alphabetic character.

* `Cldr.Number.Parser.resolve/2` and `Cldr.Number.Parser.find_and_replace/2` are made public functions.

* Add `resolve_pers/2` and `resolve_per/2` to the `MyApp.Number` module.

**Comment by DaTrader** [comment]
Thanks, it's really great to receive such a fast feedback.

I am already using the ex_cldr_territories library. Actually it was a library like this that I was looking (googling) for initially but then I discovered its siblings as well and I was so delighted that what I initially thought would take me weeks or months, suddenly became a matter of days (I completed my current version of the parser in 5+ days, thanks to your libraries).

As for the territories library, I do have some questions/suggestions.. Please note that most of the questions below are just for me to get a clearer picture on where the library development is headed to so I can plan what, when and if to implement myself around it.

1. Given the fixed and predefined hierarchy of territories and "subdivisions" in CLDR, in reality the library may not always map 1:1 to a specific UC requirements. For example, I sometimes need an additional level of precision, e.g. New England (US). Is there a plan to broaden the library scope over time (e.g. CLDR++ ;) a little bit to support custom (user-defined) territories, similar to custom/private currencies? Please note that this is not such a wild request (although, it may be delegated to a proper DB) as many larger (more commonly known) cities and subdivisions' subdivisions world-wide are also subject to locales (e.g. London in English -> Londra in Italian, Zagreb in Croatian and English, but Zagabria in Italian, etc.).

2. The "subdivisions", although politically relevant as such do not reflect the order of magnitude of their relevance when put in a particular context, not geographically, not economically (market-wise). For instance, I come from Croatia and the "subdivisions" there are hardly comparable to small counties in the US, and nowhere near the level of its states (unlike what the "subdivision" classification currently suggests when taken at face value) for Croatia in itself is a very small country, particularly population-wise. IMO, there needs to be some piece of information on subdivisions reflecting this concern.

3. It may be something that I overlooked, but I can't find a parsing function for territories in the library. There's a function to translate a territory name from one locale to another, but haven't seen one that returns its code. This really is not a big issue for I simply generate a dictionary with localized names as keys and codes as values to achieve the same effect, but was wondering anyway.

4. Default longitude / latitude coordinates in info: if not as a standard datapoint, then at least as part of the support for custom/private properties.

5. Helper functions for hierarchical navigation (i.e. universal parent/child functions for uniformly traversing the hierarchy - especially useful when/if custom subdivisions supported and/or info/1 support for subdivisions is added).

Thanks!

**Comment by DaTrader** [comment]
Just found out there's the same bug with numbers as there was with currencies prior to the last release - they get parsed even if adjacent to or in the middle of a word:

```
iex(158)> Cldr.Number.Parser.scan( "this is ok: 123")
["this is ok: ", 123]
iex(159)> Cldr.Number.Parser.scan( "th123is is not.")      
["th", 123, "is is not."]
```

**Comment by kipcole9** [comment]
This I have to think on. Extracting numbers from a string is exactly the design goal for `Cldr.Number.Parser.scan/2`. Its not a general purpose tokeniser and it has no idea of the concept of words or parts of speech.  For example, `Cldr.Number.Parser.scan("23swiss francs") should result in `[23, "swiss francs"]` I think.

The changes to resolving currencies and percent/permille made sense because they are resolved before/after a number and are therefore relevant to formulating money amounts (which was the objective).

For the territories discussion, your feedback and questions should move to the [ex_cldr_territories](https://github.com/Schultzer/cldr_territories) repository so that @Schultzer (the author) has an opportunity to comment.  However, given that these libraries primary purpose is to leverage the content in CLDR, I don't expect that there are any plans to turn it into a general purpose POI database manager.

**Comment by DaTrader** [comment]
Ok, but please let me know what you have decided so I can figure out how to deal with it. It's not a big deal for me to have my code handle this as I can check where your function returns a number and a currency atom and then only make sure it's not adjacent to any letter on the other side (I treat both USD 123.45 and 123.45 USD as money).

What do you think is the best way to check if a cross-locale unicode character is a letter and not a punctuation or any other non-letter character?

**Comment by DaTrader** [comment]
Another thing. The following sure looks like a bug - After the call of resolve_currencies/1 the string that prepends the number and/or currency is returned in lower case:

```
iex(17)> Cldr.Number.Parser.scan( "Try ThCA$2is") |> Cldr.Number.Parser.resolve_currencies()
[:TRY, " thca$", 2, "is"]
iex(18)> Cldr.Number.Parser.scan( "Try Th CA$2is") |> Cldr.Number.Parser.resolve_currencies()
[:TRY, " th ", :CAD, 2, "is"]
```

**Comment by kipcole9** [comment]
Hmmm, I'll look into that - I came across the same thing and thought I had fixed it. Thats for the additional test case.

Having thought about parsing numbers, I will hold to the current implementation. The design intent is to extract numbers anywhere in the string and therefore think sticking with that principal meets the expectations of a function called `Cldr.Number.Parser.scan/2`.

When you're looking for adjacent alphabetic characters, you can use a regex like `~r/[[:alpha:]]/u` which matches any alphabetic character in any unicode script. Don't forget to use the `u` flag at the end of the regex. To match at the beginning of the string it would be ``~r/^[[:alpha:]]/u` and at the end `~r/[[:alpha:]]$/u`.

**Comment by DaTrader** [comment]
Thanks!

**Comment by kipcole9** [comment]
As of this [commit](https://github.com/elixir-cldr/cldr_numbers/commit/869068c2a01da8123accf9eb20306903fde966bc) I believe the bug is fixed.  I'd suggest that you use `{:ex_cldr_numbers, github: "elixir-cldr/cldr_numbers"},` in your configuration for now until stability is clear in your testing and then I push a new version to `hex.pm`. That work for you?

**Comment by DaTrader** [comment]
Sure. Will do. Thanks!

**Comment by kipcole9** [comment]
Any further issues you've spotted?  If not I'll go ahead and push a new version to hex.

**Comment by DaTrader** [comment]
For the time being everything seems to work fine.
